name: Xcode Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clean
        run: xcodebuild clean -project Template.xcodeproj -configuration Debug -alltargets

      - name: Archive
        run: |
          mkdir ~/xcout
          xcodebuild archive -project Template.xcodeproj -scheme Template -configuration Debug -archivePath ~/xcout/Template.xcarchive CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
