name: Xcode Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Archive
        run: |
          mkdir ~/xcout
          xcodebuild -allowProvisioningUpdates -project Template.xcodeproj -scheme Template -archivePath ~/xcout/Template.xcarchive archive
